name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'bullseye-slim'
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: sed -i "s/{IMAGE}/${{ matrix.version }}/g" Dockerfile && docker build -t luckyraul/backupninja:${{ matrix.version }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=luckyraul/backupninja:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/auth:${{ matrix.version }}
          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo $IMAGE_ID
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID